### ISSUE TITLE
Logging into production Feigenbaum produces exception

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-exhibits-template#60]
For webauth user petucket: 

TypeError (no implicit conversion of nil into Array):
 app/models/user.rb:40:in `&'
 app/models/user.rb:40:in `create_roles_from_workgroups'
 app/models/user.rb:28:in `webauth_groups='

https://github.com/sul-dlss/sul-exhibits-template/blob/master/app/models/user.rb#L40

guard against nil?

also see https://github.com/sul-dlss/sul-exhibits-template/blob/b72fb7616a462e8a0cabc03da7d73aa14501df2b/config/initializers/devise.rb#L3-L13

**Comment by peetucket** [comment]
Settings.superadmin_workgroups aren't getting set in production ?

in local development:

$ bundle exec rails c production
Loading development environment (Rails 4.2.2)
2.2.2 :001 > Settings.superadmin_workgroups
 => ["dlss:exhibits-admin"]

in production:
$ bundle exec rails c production
Loading production environment (Rails 4.2.2)
2.2.0 :001 > Settings.superadmin_workgroups
 => nil

**Comment by peetucket** [comment]
in config/settings.yml  we’re providing our own, for some reason
https://github.com/sul-dlss/exhibits-request/blob/3313d90e5d7eec94e80d83bd64930608391b01bc/app/jobs/exhibit_capistrano_deploy_setup_job.rb#L39-L45

we should inject that into the config/settings/production.yml instead, and accept the upstream config/settings.yml.

the setting was the first actual default setting we’ve had.

**Comment by peetucket** [comment]
only affects non superadmin users
